"""empty message

Revision ID: 1f3a4b47166b
Revises: 6d51d696aada
Create Date: 2026-08-15 13:01:35.708097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1f3a4b47166b'
down_revision: Union[str, Sequence[str], None] = '6d51d696aada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.drop_column('next_payment')
        batch_op.drop_column('balance')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('last_payment')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_payment', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('next_payment', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
