"""empty message

Revision ID: 36a52164e1ca
Revises: 7dadc82dd578
Create Date: 2026-08-10 12:27:58.603192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '36a52164e1ca'
down_revision: Union[str, Sequence[str], None] = '7dadc82dd578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('bed_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenantrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_dni', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roomrecord', ['room_id'], ['id'])
        batch_op.create_foreign_key(None, 'tenantrecord', ['tenant_id'], ['id'])
        batch_op.drop_column('tenant_email')
        batch_op.drop_column('tenant_phone')
        batch_op.drop_column('status')
        batch_op.drop_column('tenant_dni')
        batch_op.drop_column('floor')
        batch_op.drop_column('bed_type')
        batch_op.drop_column('room')
        batch_op.drop_column('tenant')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('room', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bed_type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tenant_dni', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tenant_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tenant_email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('room_id')

    op.drop_table('tenantrecord')
    op.drop_table('roomrecord')
    # ### end Alembic commands ###
