"""empty message

Revision ID: 508655e2df85
Revises: 
Create Date: 2026-08-07 20:02:58.440689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '508655e2df85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adminaccount', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adminaccount_email'), ['email'], unique=True)

    op.create_table('occupancyrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('bed_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_dni', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('deposit', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_payment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_payment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lease_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lease_end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lease_term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('record_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('termination_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('termination_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("DROP TABLE IF EXISTS prueba")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prueba_pkey'))
    )
    op.drop_table('occupancyrecord')
    with op.batch_alter_table('adminaccount', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adminaccount_email'))

    op.drop_table('adminaccount')
    # ### end Alembic commands ###
