"""empty message

Revision ID: 6094e2611d53
Revises: 36a52164e1ca
Create Date: 2026-08-10 17:07:20.059814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6094e2611d53'
down_revision: Union[str, Sequence[str], None] = '36a52164e1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               nullable=False)
        batch_op.alter_column('tenant_id',
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               nullable=True)
        batch_op.alter_column('room_id',
               nullable=True)

    # ### end Alembic commands ###
