"""empty message

Revision ID: 69c93399c0c6
Revises: 1f3a4b47166b
Create Date: 2026-08-25 12:22:58.358834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '69c93399c0c6'
down_revision: Union[str, Sequence[str], None] = '1f3a4b47166b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountingentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mov_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mov_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subchapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('consum', sa.Float(), nullable=True),
    sa.Column('observ', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accountingentry')
    # ### end Alembic commands ###
