"""empty message

Revision ID: 6d51d696aada
Revises: 7815bfadb616
Create Date: 2026-08-13 20:01:58.822675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6d51d696aada'
down_revision: Union[str, Sequence[str], None] = '7815bfadb616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.drop_column('termination_reason')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termination_reason', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
