"""empty message

Revision ID: 7dadc82dd578
Revises: 508655e2df85
Create Date: 2026-08-08 16:44:29.273682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7dadc82dd578'
down_revision: Union[str, Sequence[str], None] = '508655e2df85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.drop_column('lease_term')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancyrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_term', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
