"""empty message

Revision ID: a359d5fc06f2
Revises: 69c93399c0c6
Create Date: 2026-08-29 12:34:55.337159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a359d5fc06f2'
down_revision: Union[str, Sequence[str], None] = '69c93399c0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accountingentry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accountingentry', schema=None) as batch_op:
        batch_op.drop_column('bill_url')

    # ### end Alembic commands ###
